on:
  push:
    tags: [ "*" ]
    branches:
      - main
  pull_request:
    branches: [ "**" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: demonstrationorg/ci-docker-reef-revelations

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder step for the build job."

  cleanup:
    runs-on: ubuntu-24.04
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - run: echo "✅ Log into registry status is ${{ job.status }}."

      - name: List images with specific tag
        run: |
          NAMESPACE=demonstrationorg
          REPOSITORY=ci-docker-reef-revelations
          TAG=17cd519
          curl -s -u ${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PAT }} \
          "https://hub.docker.com/v2/namespaces/${NAMESPACE}/repositories/${REPOSITORY}/tags/${TAG}/" | jq '.results[].digest'
      - run: echo "✅ Listed images with tag 17cd519."

      - name: Delete specific Docker image tag
        run: |
          NAMESPACE=demonstrationorg
          REPOSITORY=ci-docker-reef-revelations
          TAG=17cd519
          curl -s -X DELETE -u ${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PAT }} \
          "https://hub.docker.com/v2/repositories/${NAMESPACE}/${REPOSITORY}/tags/${TAG}/"
      - run: echo "✅ Deleted images with tag 17cd519."