name: gha-cleanup-dh-prune

on:
    push:
      tags: [ "*" ]
      branches:
        - main
    pull_request:
      branches: [ "**" ]

env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Your existing build steps here

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Delete specific Docker image tag
        run: |
          IMAGE_NAME=${{ secrets.ORGANIZATION}}/${{ secrets.IMAGE_NAME }}
          TAG=17cd519
          curl -s -X DELETE -u ${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PAT }} \
          "https://hub.docker.com/v2/repositories/${{ secrets.ORGANIZATION }}/${{ secrets.IMAGE_NAME }}/tags/${TAG}/"
      