name: gha-build_image_remediate_ci
on:
  push:
    tags: [ "*" ]
    branches:
      - main
  pull_request:
    branches: [ "**" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: demonstrationorg/ci-docker-reef-revelations

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder step for the build job."

  cleanup:
    runs-on: ubuntu-24.04
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - run: echo "✅ Log into registry status is ${{ job.status }}."

      - name: List all image tags in the repository
        run: |
          NAMESPACE=demonstrationorg
          REPOSITORY=ci-docker-reef-revelations
          curl -s -u ${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PAT }} \
          "https://hub.docker.com/v2/namespaces/${NAMESPACE}/repositories/${REPOSITORY}/tags/" | jq '.results[].name'
      - run: echo "✅ Listed all image tags in the repository."

     