name: gha-build_image_remediate_ci
on:
  push:
    tags: [ "*" ]
    branches:
      #- 'main'
      - main
      #- branch-* 
  pull_request:
    branches: [ "**" ]
    
env:
  #sonar 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.ORGANIZATION}}/${{ secrets.IMAGE_NAME }}
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  # Use `latest` as the tag to compare to if empty, assuming that it's already pushed
  COMPARE_TAG: latest
  # add flag for build summary
  #DOCKER_BUILD_NO_SUMMARY: false

  
jobs:
  build:

    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      pull-requests: write


  post-build-checks:
    needs: [build]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      pull-requests: write
      security-events: write
      
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{github.event_name }} event."
      - run: echo "🐧 This job is now running!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
    
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 List files in the repository status is ${{ job.status }}."

          
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - run: echo "✅ Log into registry  status is ${{ job.status }}."

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            type=edge,branch=$repo.default_branch
            type=semver,pattern=v{{version}}
            type=sha,prefix=,suffix=,format=short
      - run: echo "✅ Extract Docker metadata status is ${{ job.status }}."

      - name: Set up Docker Build Cloud se-cloud-builder Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "demonstrationorg/default"
      - run: echo "✅ Set Up Docker Build Cloud cloud-demonstrationorg-default Buildx status is ${{ job.status }}."
      
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          load: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64,linux/arm64"
          sbom: true
          provenance: true

        # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
      - run: echo "✅ Build and push Docker image status is ${{ job.status }}."
    
      

    # Docker Scout display a quickview, cves, recommendations output
      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1.17.1
        with:
          command: quickview, cves, recommendations
          image: ${{ steps.meta.outputs.tags }}
          sarif-file: sarif.output.json
          platform: "linux/arm64"
          summary: true
      - run: echo "✅ DOCKER SCOUT Analysis - QuickView, CVEs and Recommendations status is ${{ job.status }}."


    # Compare the image built in the pull request with the one in production
      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1.17.1
        with:
          command: compare, recommendations, attestation-add
          image: ${{ steps.meta.outputs.tags }}
          only-severities: critical,high,medium
          exit-code: true
          summary: true
      - run: echo "✅ DOCKER SCOUT Analysis compare image status is ${{ job.status }}."

      # Validate scan results and block if vulnerabilities are found
      - name: Validate Docker Scout scan results
        if: ${{ github.event_name != 'pull_request_target' }}
        run: |
          if [ "${{ steps.docker-scout-cves.outcome }}" == "failure" ]; then
            echo "⚠️ Critical or high or medium severity vulnerabilities detected!"
            echo "Please review the Docker Scout analysis results above."
            exit 1
          fi
      - run: echo "✅ Validate DOCKER SCOUT Scan results status is ${{ job.status }}."

      - name: Advanced Docker Scout Analysis
        id: docker-scout-advanced
        uses: docker/scout-action@v1.17.1  
        with:
          command: analyze
          image: ${{ steps.meta.outputs.tags }}
          only-severities: critical,high
          sarif-file: docker-scout.sarif
          summary: true
      - run: echo "✅ Advanced Docker Scout Analysis status is ${{ job.status }}."

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: docker-scout.sarif
          category: Docker-Scout
      - run: echo "✅ Upload SARIF report status is ${{ job.status }}."

     
      - name: SBOMs Comparison
        uses: docker/scout-action@v1.17.1
        with:
          command: compare
          image: ${{ steps.meta.outputs.tags }}
          to-ref: type=ref,ref=prod
          format: sarif
          #output-file: sbom-diff.sarif
          sarif-file: docker-scout.sarif
      - run: echo "✅ SBOMs Comparison status is ${{ job.status }}."


      - name: Block Deployment on Failures
        if: ${{ failure() }}
        run: |
          echo "🛑 Post-build security checks failed!"
          echo "Review Docker Scout analysis results above."
          exit 1

      - name: Notify on Success
        if: success()
        run: |
          echo "✅ All security checks passed"
          echo "Image is cleared for production deployment"